"""Add custom_data column to Protocol model

Revision ID: 179eeb1ccbcd
Revises: 23c25ec7966d
Create Date: 2022-03-29 18:35:52.637825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '179eeb1ccbcd'
down_revision = '23c25ec7966d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocol', sa.Column('custom_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocol', 'custom_data')
    # ### end Alembic commands ###
