"""Add model for databases

Revision ID: 306f1f7290fc
Revises: 5aa226bc5778
Create Date: 2021-12-29 21:37:31.931805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306f1f7290fc'
down_revision = '5aa226bc5778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_id'), 'database', ['id'], unique=False)
    op.create_index(op.f('ix_database_name'), 'database', ['name'], unique=False)
    op.create_index(op.f('ix_database_owner'), 'database', ['owner'], unique=False)
    op.create_index(op.f('ix_database_owner_id'), 'database', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_owner_id'), table_name='database')
    op.drop_index(op.f('ix_database_owner'), table_name='database')
    op.drop_index(op.f('ix_database_name'), table_name='database')
    op.drop_index(op.f('ix_database_id'), table_name='database')
    op.drop_table('database')
    # ### end Alembic commands ###
