"""Add retention_policy column to Database model

Revision ID: c1dffe177dcd
Revises: 756ad0701488
Create Date: 2022-02-10 17:29:32.544909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dffe177dcd'
down_revision = '756ad0701488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database', sa.Column('retention_policy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database', 'retention_policy')
    # ### end Alembic commands ###
