"""Add custom_data column to Protocol model

Revision ID: 54a58d1658ca
Revises: 3046b45f358f
Create Date: 2022-03-29 18:46:56.472451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54a58d1658ca'
down_revision = '3046b45f358f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('custom_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_id'), 'protocol', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_owner'), 'protocol', ['owner'], unique=False)
    op.create_index(op.f('ix_protocol_owner_id'), 'protocol', ['owner_id'], unique=False)
    op.create_index(op.f('ix_protocol_title'), 'protocol', ['title'], unique=False)
    op.create_table('protocolservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolservice_id'), 'protocolservice', ['id'], unique=False)
    op.create_index(op.f('ix_protocolservice_uuid'), 'protocolservice', ['uuid'], unique=False)
    op.create_table('protocolfeature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['protocolservice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolfeature_id'), 'protocolfeature', ['id'], unique=False)
    op.create_index(op.f('ix_protocolfeature_identifier'), 'protocolfeature', ['identifier'], unique=False)
    op.create_table('protocolcommand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('observable', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.Boolean(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['protocolfeature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolcommand_id'), 'protocolcommand', ['id'], unique=False)
    op.create_index(op.f('ix_protocolcommand_identifier'), 'protocolcommand', ['identifier'], unique=False)
    op.create_table('protocolproperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('observable', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.Boolean(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['protocolfeature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolproperty_id'), 'protocolproperty', ['id'], unique=False)
    op.create_index(op.f('ix_protocolproperty_identifier'), 'protocolproperty', ['identifier'], unique=False)
    op.create_table('protocolparameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['protocolcommand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolparameter_id'), 'protocolparameter', ['id'], unique=False)
    op.create_index(op.f('ix_protocolparameter_identifier'), 'protocolparameter', ['identifier'], unique=False)
    op.create_table('protocolresponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['protocolcommand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolresponse_id'), 'protocolresponse', ['id'], unique=False)
    op.create_index(op.f('ix_protocolresponse_identifier'), 'protocolresponse', ['identifier'], unique=False)
    op.add_column('job', sa.Column('list_protocol_and_database', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('scheduledjob', sa.Column('list_protocol_and_database', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduledjob', 'list_protocol_and_database')
    op.drop_column('job', 'list_protocol_and_database')
    op.drop_index(op.f('ix_protocolresponse_identifier'), table_name='protocolresponse')
    op.drop_index(op.f('ix_protocolresponse_id'), table_name='protocolresponse')
    op.drop_table('protocolresponse')
    op.drop_index(op.f('ix_protocolparameter_identifier'), table_name='protocolparameter')
    op.drop_index(op.f('ix_protocolparameter_id'), table_name='protocolparameter')
    op.drop_table('protocolparameter')
    op.drop_index(op.f('ix_protocolproperty_identifier'), table_name='protocolproperty')
    op.drop_index(op.f('ix_protocolproperty_id'), table_name='protocolproperty')
    op.drop_table('protocolproperty')
    op.drop_index(op.f('ix_protocolcommand_identifier'), table_name='protocolcommand')
    op.drop_index(op.f('ix_protocolcommand_id'), table_name='protocolcommand')
    op.drop_table('protocolcommand')
    op.drop_index(op.f('ix_protocolfeature_identifier'), table_name='protocolfeature')
    op.drop_index(op.f('ix_protocolfeature_id'), table_name='protocolfeature')
    op.drop_table('protocolfeature')
    op.drop_index(op.f('ix_protocolservice_uuid'), table_name='protocolservice')
    op.drop_index(op.f('ix_protocolservice_id'), table_name='protocolservice')
    op.drop_table('protocolservice')
    op.drop_index(op.f('ix_protocol_title'), table_name='protocol')
    op.drop_index(op.f('ix_protocol_owner_id'), table_name='protocol')
    op.drop_index(op.f('ix_protocol_owner'), table_name='protocol')
    op.drop_index(op.f('ix_protocol_id'), table_name='protocol')
    op.drop_table('protocol')
    # ### end Alembic commands ###
