"""Base

Revision ID: 136683ba1818
Revises: 
Create Date: 2021-10-28 08:54:26.019128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '136683ba1818'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('flow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_description'), 'flow', ['description'], unique=False)
    op.create_index(op.f('ix_flow_id'), 'flow', ['id'], unique=False)
    op.create_index(op.f('ix_flow_title'), 'flow', ['title'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_description'), 'item', ['description'], unique=False)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.create_table('job',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('flow_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('execute_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_job_created_at'), 'job', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_description'), 'job', ['description'], unique=False)
    op.create_index(op.f('ix_job_execute_at'), 'job', ['execute_at'], unique=False)
    op.create_index(op.f('ix_job_flow_id'), 'job', ['flow_id'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.create_index(op.f('ix_job_uuid'), 'job', ['uuid'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_description'), 'service', ['description'], unique=False)
    op.create_index(op.f('ix_service_hostname'), 'service', ['hostname'], unique=False)
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_index(op.f('ix_service_ip'), 'service', ['ip'], unique=False)
    op.create_index(op.f('ix_service_port'), 'service', ['port'], unique=False)
    op.create_index(op.f('ix_service_service_uuid'), 'service', ['service_uuid'], unique=False)
    op.create_index(op.f('ix_service_title'), 'service', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_title'), table_name='service')
    op.drop_index(op.f('ix_service_service_uuid'), table_name='service')
    op.drop_index(op.f('ix_service_port'), table_name='service')
    op.drop_index(op.f('ix_service_ip'), table_name='service')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_index(op.f('ix_service_hostname'), table_name='service')
    op.drop_index(op.f('ix_service_description'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_job_uuid'), table_name='job')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_flow_id'), table_name='job')
    op.drop_index(op.f('ix_job_execute_at'), table_name='job')
    op.drop_index(op.f('ix_job_description'), table_name='job')
    op.drop_index(op.f('ix_job_created_at'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_description'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_flow_title'), table_name='flow')
    op.drop_index(op.f('ix_flow_id'), table_name='flow')
    op.drop_index(op.f('ix_flow_description'), table_name='flow')
    op.drop_table('flow')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
