"""Remove foreign key constraint from Protocol and Database models

Revision ID: 1819609e400a
Revises: 1aa828d34af6
Create Date: 2022-04-10 14:33:32.263585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1819609e400a'
down_revision = '1aa828d34af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('database_job_id_fkey', 'database', type_='foreignkey')
    op.drop_constraint('protocol_job_id_fkey', 'protocol', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('protocol_job_id_fkey', 'protocol', 'job', ['job_id'], ['id'])
    op.create_foreign_key('database_job_id_fkey', 'database', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###
