"""Update of Job relation

Revision ID: 260e30c66784
Revises: 0f06ca144817
Create Date: 2021-10-23 14:44:35.975862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '260e30c66784'
down_revision = '0f06ca144817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_description'), 'flow', ['description'], unique=False)
    op.create_index(op.f('ix_flow_id'), 'flow', ['id'], unique=False)
    op.create_index(op.f('ix_flow_title'), 'flow', ['title'], unique=False)
    op.add_column('job', sa.Column('flow_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_job_flow_id'), 'job', ['flow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_flow_id'), table_name='job')
    op.drop_column('job', 'flow_id')
    op.drop_index(op.f('ix_flow_title'), table_name='flow')
    op.drop_index(op.f('ix_flow_id'), table_name='flow')
    op.drop_index(op.f('ix_flow_description'), table_name='flow')
    op.drop_table('flow')
    # ### end Alembic commands ###
