"""Add dataflow_path to job models

Revision ID: 4b4ed8f6c351
Revises: 1819609e400a
Create Date: 2022-05-11 16:27:34.168155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4ed8f6c351'
down_revision = '1819609e400a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('dataflow_path', sa.String(), nullable=True))
    op.add_column('scheduledjob', sa.Column('dataflow_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduledjob', 'dataflow_path')
    op.drop_column('job', 'dataflow_path')
    # ### end Alembic commands ###
