"""Remove relationships

Revision ID: 544647392f9b
Revises: 5bc45dc5b4ca
Create Date: 2021-12-28 11:56:36.018718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544647392f9b'
down_revision = '5bc45dc5b4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_workflow_id'), 'job', ['workflow_id'], unique=False)
    op.drop_constraint('job_workflow_id_fkey', 'job', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('job_workflow_id_fkey', 'job', 'workflow', ['workflow_id'], ['id'])
    op.drop_index(op.f('ix_job_workflow_id'), table_name='job')
    # ### end Alembic commands ###
