"""Chnage job model

Revision ID: 5bc45dc5b4ca
Revises: f1a29cfdc28a
Create Date: 2021-12-28 11:40:59.064465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc45dc5b4ca'
down_revision = 'f1a29cfdc28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('owner', sa.String(), nullable=True))
    op.create_index(op.f('ix_job_owner'), 'job', ['owner'], unique=False)
    op.create_index(op.f('ix_job_owner_id'), 'job', ['owner_id'], unique=False)
    op.drop_constraint('job_owner_id_fkey', 'job', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('job_owner_id_fkey', 'job', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_job_owner_id'), table_name='job')
    op.drop_index(op.f('ix_job_owner'), table_name='job')
    op.drop_column('job', 'owner')
    # ### end Alembic commands ###
