"""Add flow

Revision ID: 5d8ffb895d68
Revises: d4867f3a4c0a
Create Date: 2021-10-22 09:15:59.690529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d8ffb895d68'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_description'), 'flow', ['description'], unique=False)
    op.create_index(op.f('ix_flow_id'), 'flow', ['id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_description'), 'service', ['description'], unique=False)
    op.create_index(op.f('ix_service_hostname'), 'service', ['hostname'], unique=False)
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_index(op.f('ix_service_ip'), 'service', ['ip'], unique=False)
    op.create_index(op.f('ix_service_port'), 'service', ['port'], unique=False)
    op.create_index(op.f('ix_service_service_uuid'), 'service', ['service_uuid'], unique=False)
    op.create_index(op.f('ix_service_title'), 'service', ['title'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_service_title'), table_name='service')
    op.drop_index(op.f('ix_service_service_uuid'), table_name='service')
    op.drop_index(op.f('ix_service_port'), table_name='service')
    op.drop_index(op.f('ix_service_ip'), table_name='service')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_index(op.f('ix_service_hostname'), table_name='service')
    op.drop_index(op.f('ix_service_description'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_flow_id'), table_name='flow')
    op.drop_index(op.f('ix_flow_description'), table_name='flow')
    op.drop_table('flow')
    # ### end Alembic commands ###
