"""Add scheduled_job model

Revision ID: 5f142c9e534d
Revises: d5b54d83680e
Create Date: 2022-02-11 14:55:32.685905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.scheduled_job import IntEnum, ScheduledJobStatus

# revision identifiers, used by Alembic.
revision = '5f142c9e534d'
down_revision = 'd5b54d83680e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('workflows', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('execute_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('job_status', IntEnum(ScheduledJobStatus), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduledjob_created_at'), 'scheduledjob', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduledjob_execute_at'), 'scheduledjob', ['execute_at'], unique=False)
    op.create_index(op.f('ix_scheduledjob_id'), 'scheduledjob', ['id'], unique=False)
    op.create_index(op.f('ix_scheduledjob_owner'), 'scheduledjob', ['owner'], unique=False)
    op.create_index(op.f('ix_scheduledjob_owner_id'), 'scheduledjob', ['owner_id'], unique=False)
    op.create_index(op.f('ix_scheduledjob_scheduled_at'), 'scheduledjob', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduledjob_title'), 'scheduledjob', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduledjob_title'), table_name='scheduledjob')
    op.drop_index(op.f('ix_scheduledjob_scheduled_at'), table_name='scheduledjob')
    op.drop_index(op.f('ix_scheduledjob_owner_id'), table_name='scheduledjob')
    op.drop_index(op.f('ix_scheduledjob_owner'), table_name='scheduledjob')
    op.drop_index(op.f('ix_scheduledjob_id'), table_name='scheduledjob')
    op.drop_index(op.f('ix_scheduledjob_execute_at'), table_name='scheduledjob')
    op.drop_index(op.f('ix_scheduledjob_created_at'), table_name='scheduledjob')
    op.drop_table('scheduledjob')
    # ### end Alembic commands ###
