"""we fixed something

Revision ID: 612fca923404
Revises: a81f7f7dc1eb
Create Date: 2021-10-23 16:36:03.006837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '612fca923404'
down_revision = 'a81f7f7dc1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('flow_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('execute_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_job_created_at'), 'job', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_description'), 'job', ['description'], unique=False)
    op.create_index(op.f('ix_job_execute_at'), 'job', ['execute_at'], unique=False)
    op.create_index(op.f('ix_job_flow_id'), 'job', ['flow_id'], unique=False)
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    op.create_index(op.f('ix_job_uuid'), 'job', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_uuid'), table_name='job')
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_index(op.f('ix_job_flow_id'), table_name='job')
    op.drop_index(op.f('ix_job_execute_at'), table_name='job')
    op.drop_index(op.f('ix_job_description'), table_name='job')
    op.drop_index(op.f('ix_job_created_at'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
