"""renamed flow col to flow2 for testing

Revision ID: 849570401320
Revises: 260e30c66784
Create Date: 2021-10-23 16:06:38.050373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '849570401320'
down_revision = '260e30c66784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('flow2', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('job', 'flow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('job', 'flow2')
    # ### end Alembic commands ###
