"""Add job_id column to Protocol and add Database model

Revision ID: 8ee2b6d6cfe0
Revises: d2deb9a94fe8
Create Date: 2022-03-13 13:26:26.342472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee2b6d6cfe0'
down_revision = 'd2deb9a94fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('retention_policy', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_id'), 'database', ['id'], unique=False)
    op.create_index(op.f('ix_database_owner'), 'database', ['owner'], unique=False)
    op.create_index(op.f('ix_database_owner_id'), 'database', ['owner_id'], unique=False)
    op.create_index(op.f('ix_database_title'), 'database', ['title'], unique=False)
    op.add_column('protocol', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'protocol', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'protocol', type_='foreignkey')
    op.drop_column('protocol', 'job_id')
    op.drop_index(op.f('ix_database_title'), table_name='database')
    op.drop_index(op.f('ix_database_owner_id'), table_name='database')
    op.drop_index(op.f('ix_database_owner'), table_name='database')
    op.drop_index(op.f('ix_database_id'), table_name='database')
    op.drop_table('database')
    # ### end Alembic commands ###
