"""renamed flow2 back to flow

Revision ID: a81f7f7dc1eb
Revises: 849570401320
Create Date: 2021-10-23 16:07:34.134068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a81f7f7dc1eb'
down_revision = '849570401320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('flow', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('job', 'flow2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('flow2', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('job', 'flow')
    # ### end Alembic commands ###
