"""Create job-workflow relationship and cascade delete

Revision ID: b8808333e331
Revises: aca59ea861d3
Create Date: 2022-03-09 13:37:27.196269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8808333e331'
down_revision = 'aca59ea861d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_job_id_fkey', 'workflow', type_='foreignkey')
    op.create_foreign_key(None, 'workflow', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.create_foreign_key('workflow_job_id_fkey', 'workflow', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###
