"""Change fileName to file_name

Revision ID: d5b54d83680e
Revises: c5fa78dcf257
Create Date: 2022-02-02 13:24:39.498240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b54d83680e'
down_revision = 'c5fa78dcf257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('file_name', sa.String(), nullable=True))
    op.drop_column('workflow', 'fileName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('fileName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workflow', 'file_name')
    # ### end Alembic commands ###
