"""Change fileName to file_name

Revision ID: 5ddd1d2095ae
Revises: 5491d30e4ebb
Create Date: 2022-02-02 13:23:54.636777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddd1d2095ae'
down_revision = '5491d30e4ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('file_name', sa.String(), nullable=True))
    op.drop_index('ix_workflow_fileName', table_name='workflow')
    op.create_index(op.f('ix_workflow_file_name'), 'workflow', ['file_name'], unique=False)
    op.drop_column('workflow', 'fileName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('fileName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workflow_file_name'), table_name='workflow')
    op.create_index('ix_workflow_fileName', 'workflow', ['fileName'], unique=False)
    op.drop_column('workflow', 'file_name')
    # ### end Alembic commands ###
