"""First revision

Revision ID: 7d5de0772a10
Revises: 
Create Date: 2021-11-15 17:53:12.170665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5de0772a10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fileName', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_description'), 'workflow', ['description'], unique=False)
    op.create_index(op.f('ix_workflow_fileName'), 'workflow', ['fileName'], unique=False)
    op.create_index(op.f('ix_workflow_id'), 'workflow', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_name'), 'workflow', ['name'], unique=False)
    op.create_index(op.f('ix_workflow_owner'), 'workflow', ['owner'], unique=False)
    op.create_index(op.f('ix_workflow_owner_id'), 'workflow', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_owner_id'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_owner'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_name'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_id'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_fileName'), table_name='workflow')
    op.drop_index(op.f('ix_workflow_description'), table_name='workflow')
    op.drop_table('workflow')
    # ### end Alembic commands ###
