"""Update Feature table string length

Revision ID: bebedd03e40c
Revises: 875f08d81f79
Create Date: 2022-03-21 16:10:49.250154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebedd03e40c'
down_revision = '875f08d81f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('features', 'owner_uuid',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'category',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'feature_version',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'maturity_level',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'originator',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'sila2_version',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'identifier',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'display_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    op.alter_column('features', 'locale',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('features', 'locale',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'description',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'display_name',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'identifier',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'sila2_version',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'originator',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'maturity_level',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'feature_version',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'category',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('features', 'owner_uuid',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
