"""Update Feature tabl

Revision ID: e7fb92370e5c
Revises: ecb60e2bea3c
Create Date: 2022-03-21 16:05:50.956409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fb92370e5c'
down_revision = 'ecb60e2bea3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('features_owner_uuid_fkey', 'features', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('features_owner_uuid_fkey', 'features', 'service_info', ['owner_uuid'], ['uuid'])
    # ### end Alembic commands ###
