"""Update ServiceInfo: Add column name

Revision ID: ecb60e2bea3c
Revises: 2f2c04bbe1ad
Create Date: 2022-03-18 22:42:26.473554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb60e2bea3c'
down_revision = '2f2c04bbe1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_info', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_info', 'name')
    # ### end Alembic commands ###
